version: '3'
services:
  app:
    build:
      context: .
      args:
        DATA_PATH: /data
        BUILD_PATH: /build
    container_name: cloud-drive
    image: cloud-drive:latest
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./data:/app/data

networks:
  backend:
